ARCHS = armv7 armv7s arm64
include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = ReachAppFlipswitch
ReachAppFlipswitch_FILES = Switch.x
ReachAppFlipswitch_FRAMEWORKS = UIKit
ReachAppFlipswitch_LIBRARIES = flipswitch
ReachAppFlipswitch_INSTALL_PATH = /Library/Switches

include $(THEOS_MAKE_PATH)/bundle.mk