ARCHS = armv7 arm64
include theos/makefiles/common.mk

TOOL_NAME = ReachAppKeyboardDaemon
ReachAppKeyboardDaemon_FILES = main.mm
ReachAppKeyboardDaemon_PRIVATE_FRAMEWORKS = AppSupport

include $(THEOS_MAKE_PATH)/tool.mk
