#!/bin/bash

chgrp wheel /Library/LaunchDaemons/com.efrederickson.reachapp.fsdaemon.plist
chown root /Library/LaunchDaemons/com.efrederickson.reachapp.fsdaemon.plist
launchctl load -w /Library/LaunchDaemons/com.efrederickson.reachapp.fsdaemon.plist

echo "The best multitasker you've never used... Until now."