ARCHS = armv7 armv7s arm64
CFLAGS = -I../

include theos/makefiles/common.mk

TOOL_NAME = ReachAppFSDaemon
ReachAppFSDaemon_FILES = main.mm
ReachAppFSDaemon_PRIVATE_FRAMEWORKS = MobileCoreServices

include $(THEOS_MAKE_PATH)/tool.mk
